### ISSUE TITLE
Transfert not working

### ISSUE THREAD

**Issue by nifloutch** [OpenPoGo/OpenPoGoBot#328]
### Expected Behavior

When I capture a Pokemon, if it matches transfert rules then it gets transferred right away
### Actual Behavior

The transfert happens when I start the bot, but after that my pokemons aren't transferred anymore. So it ends up with my bag being full and the bot kinda dead locked.
### Steps to Reproduce

Here is the start of my transfert_pokemon.yml

```
# Set to true to transfer Pokemon when bot starts.
transfer_on_start: true
use_always_keep_filter: true
use_cp_iv_filter: true

# TODO: More sensible defaults for this
always_keep:
    Mew:
        keep: true
    Mewtwo:
        keep: true

# TODO: More sensible defaults for this
cp_iv_rules:
    # default rule if Pokemon isn't in list
    default:
        release_below_cp: 2500
        release_below_iv: 0.9
        logic: or
    Lapras:
        release_below_cp: 2500
        release_below_iv: 0.9
        logic: or
```

And every pokemon have the same rule : 2500 or 0.9
### Other Information

OS: Debian 8
Git Commit: last master
